name: Auto Sync Changes

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Pull changes
        run: |
          git pull --rebase
        continue-on-error: true

      - name: Check status
        run: git status

      - name: Add changes
        run: |
          git add .
          git status

      - name: Commit changes
        run: |
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
