name: Auto Commit and Push

on:
  push:
    branches:
      - main  # You can change this to the branch you want to monitor

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Make changes (example change)
      run: |
        echo "Automated commit at $(date)" >> automated_commit_log.txt

    - name: Add, commit, and push changes
      run: |
        git add .
        git commit -m "Automated commit on $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
