name: Auto Sync Changes

on:
  push:
    branches:
      - main  # Monitor changes to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Pull, commit, push changes
        run: |
          git pull --rebase
          git add .
          git commit -m "Automated commit on $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
